#pragma once
#include "Basic.hxx"


#define __FANTASIA_COMMON_DETAIL_BEGIN \
    ___FANTASIA_DETAIL_BEGIN


#define __FANTASIA_COMMON_DETAIL_END \
    ___FANTASIA_DETAIL_END


#define __FANTASIA_COMMON_BEGIN \
    ___FANTASIA_BEGIN \


#define __FANTASIA_COMMON_END \
    ___FANTASIA_END
