#pragma once
#include "Basic.hxx"


#define _FANTASIA_FOUNDATION_DETAIL_BEGIN \
    _FANTASIA_DETAIL_BEGIN

#define _FANTASIA_FOUNDATION_DETAIL_END \
    _FANTASIA_DETAIL_END


#define _FANTASIA_FOUNDATION_BEGIN \
    _FANTASIA_BEGIN \

#define _FANTASIA_FOUNDATION_END \
    } 
