#pragma once
#include "Basic.hxx"


#define __FANTASIA_FOUNDATION_DETAIL_BEGIN \
    ___FANTASIA_DETAIL_BEGIN

#define __FANTASIA_FOUNDATION_DETAIL_END \
    ___FANTASIA_DETAIL_END


#define __FANTASIA_FOUNDATION_BEGIN \
    ___FANTASIA_BEGIN \

#define __FANTASIA_FOUNDATION_END \
    ___FANTASIA_END


__FANTASIA_FOUNDATION_BEGIN
struct Bool;
struct Float64;
struct Int64;
struct String;
__FANTASIA_FOUNDATION_END
